title: PyPUG Githubbers
githubbers:
  - pydanny
  - titopao
  - marconi
  - marksteve
  - arscariosus
  - audreyr
  - holycattle
  - fevgcastro
  - codemickeycode
  - iamanepicHERO
  - royevangelista
  - brainv
  - skytreader
  - norbertc
  - yowmamasita
  - mykromo
  - ronbeltran
  - marlonstrongcode
  - dannycastonguay
  - jpalala
  - kentwait
  - htavenido
  - jacarandang
  - stoned-code-warrior
  - edgarfelizmenio
  - maranas
  - six519
  - john2x
  - jpanganiban
  - phektus
  - mrvaldez
  - cocoy
  - itsromack
  - tropakosideadman
  - rukku
  - straycat2001
  - rlcardeno
  - jjmontalbo
  - pageman
  - jmmaranan
  - lyescorial
  - itsacezon
  - GallarinKevin
  - kendaganio
  - tinio
  - darylyu
  - iamteem
  - koalalorenzo
  - genescissors
